### REQ.1 -  Add an order 
POST  http://localhost:8083/api/orders HTTP/1.1
content-type: application/json

{
    "id": "04",
    "userId": "C008",
    "pizzaCode": "P121",   
    "pizzaQuantity": 6,
    "address": "Tartu, Narva, 23 - 11" 
}


### REQ.2 - Update an orders status to ready 
PUT  http://localhost:8084/api/orders HTTP/1.1
content-type: application/json

{
    "id": "03",
    "userId": "C007",
    "pizzaCode": "P121",   
    "pizzaQuantity": 6 
}


### REQ.3 - Get avilable deliveries
GET http://localhost:8085/api/delivery

#####################
